format = "$directory$custom$kubernetes$fill$time$cmd_duration$line_break$character"
palette = "catppuccin_mocha"

[directory]
truncation_length = 4
style = "bold lavender"

[fill]
symbol = " "

[time]
disabled = false
format = '[$time]($style) '
time_format = '%T'
style = "bold peach"

[custom.mise]
detect_files = [".mise.toml", ".mise.local.toml"]
symbol = "Î»"
format = "[$symbol]($style) "
style = "bold mauve"

[kubernetes]
disabled = false
detect_folders = ["k8s"]
detect_env_vars = ["INVALID"]                             # this is a workaround, in 1.20 it will be fixed
format = "[$symbol$context in \\($namespace\\)]($style) "
style = "bold blue"


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
