[tasks.zellij]
description = "zellij"
run = 'zellij --layout code attach --create "$(basename "$(dirname "$(git rev-parse --path-format=absolute --git-common-dir)")")-$(git branch --show-current)"'

[hooks]
enter = "if [ -z ${ZELLIJ} ]; then mise run zellij; fi"
