[tools]
node = "latest"
pnpm = "latest"
yarn = "latest"
k6 = "latest"
ruby = "latest"
python = "latest"
sqlite = "latest"
jq = "latest"
yq = "latest"
ripgrep = "latest"
gh = "latest"
claude-code = "latest"
