#!/bin/zsh -eo pipefail

/opt/homebrew/bin/mise exec -- gitleaks git --pre-commit --staged --no-banner --config ~/.config/git/gitleaks.toml --gitleaks-ignore-path ~/.config/git -v

pattern="\.\.\/\.\.\/terraform\/modules"
count=$(git diff --cached --name-only | grep -v "pre-commit" | xargs -r git diff --cached 2>/dev/null | grep -c "$pattern" || true)
if [ "$count" -gt 0 ]; then
    echo "Error: Found $count occurrence(s) of relative terraform module paths in staged changes"
    exit 1
fi
