#!/bin/zsh -eo pipefail

~/.local/share/mise/installs/gitleaks/latest/bin/gitleaks detect --no-banner --gitleaks-ignore-path ~/.config/git --log-opts="--branches=$(git rev-parse --abbrev-ref HEAD)" -v

