# Installed to: ~/.config/mise/conf.d/devenv.toml

[settings]
ruby.compile = false

[env]
SAMMY_SSH_USER = "ricardo"
HAL_1P_ACCOUNT_ID = "GHXJDH3PVNHG3PLWLS5RT4HOHI"
HAL_1P_STAGING = "op://Employee/Ghost - staging"
HAL_1P_PRODUCTION = "op://Employee/Ghost - production"
LINEAR_API_KEY = "{{ exec(command='security find-generic-password -s mise -a mise-linear-api-key -w 2>/dev/null || true') }}"
SOPS_AGE_KEY = "{{ exec(command='security find-generic-password -s mise -a mise-age-sops-key -w 2>/dev/null || true') }}"
TF_VAR_SOPS_AGE_KEY = "{{ exec(command='security find-generic-password -s mise -a mise-age-sops-key -w 2>/dev/null || true') }}\n"
TF_VAR_DIGITALOCEAN_TOKEN = "{{ exec(command='security find-generic-password -s mise -a mise-digitalocean-token -w 2>/dev/null || true') }}"
TF_VAR_FASTLY_API_KEY = "{{ exec(command='security find-generic-password -s mise -a mise-fastly-api-key -w 2>/dev/null || true') }}"
TF_VAR_SIGSCI_EMAIL = "{{ exec(command='security find-generic-password -s mise -a mise-sigsci-email -w 2>/dev/null || true') }}"
TF_VAR_SIGSCI_AUTH_TOKEN = "{{ exec(command='security find-generic-password -s mise -a mise-sigsci-auth-token -w 2>/dev/null || true') }}"
